// scripts/add-project.mjs — CLI for adding a new project to the Data Hub.
// Creates a project YAML, summary template, and outputs next steps.
// Does NOT write real credentials — those go in GitHub Secrets.

import fs from "node:fs/promises";
import path from "node:path";
import { assertSafeSlug, PROJECTS_DIR } from "../lib/config.mjs";

const TEMPLATES_DIR = path.resolve(".", "templates");

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--slug") args.slug = argv[++i];
    else if (arg === "--title") args.title = argv[++i];
    else if (arg === "--base-key") args.baseKey = argv[++i];
    else if (arg === "--group") args.group = argv[++i];
    else if (arg === "--schedule") args.schedule = argv[++i];
    else if (arg === "--description") args.description = argv[++i];
    else if (arg === "--help" || arg === "-h") args.help = true;
  }
  return args;
}

function usage() {
  console.log(`用法: npm run project:add -- --slug <slug> --title "标题" --base-key <key> [options]

必填参数:
  --slug <slug>           项目 slug (小写字母、数字、连字符)
  --title "标题"           项目标题
  --base-key <key>         飞书 Base 在注册表中的 key

可选参数:
  --group <group>          项目分组 (默认: general)
  --schedule <tier>        同步频率: hourly | daily (默认: hourly)
  --description "描述"      项目描述

示例:
  npm run project:add -- --slug reading-notes --title "阅读笔记" --base-key reading-notes --group knowledge --schedule daily
`);
}

async function main() {
  const args = parseArgs(process.argv);

  if (args.help) { usage(); return; }

  if (!args.slug || !args.title || !args.baseKey) {
    console.error("错误：缺少必填参数");
    usage();
    process.exitCode = 1;
    return;
  }

  assertSafeSlug(args.slug, "项目 slug");

  // Check project doesn't already exist
  const projectYamlPath = path.join(PROJECTS_DIR, `${args.slug}.yaml`);
  try {
    await fs.access(projectYamlPath);
    console.error(`错误：项目 ${args.slug} 已存在 (${projectYamlPath})`);
    process.exitCode = 1;
    return;
  } catch { /* good, doesn't exist */ }

  // Read template
  let template;
  try {
    template = await fs.readFile(path.join(TEMPLATES_DIR, "project.example.yaml"), "utf8");
  } catch {
    // Fallback: generate inline
    template = generateProjectYaml(args);
  }

  // Replace placeholders
  const yaml = template
    .replace(/\{\{slug\}\}/g, args.slug)
    .replace(/\{\{title\}\}/g, args.title)
    .replace(/\{\{description\}\}/g, args.description || "")
    .replace(/\{\{group\}\}/g, args.group || "general")
    .replace(/\{\{base_key\}\}/g, args.baseKey)
    .replace(/\{\{schedule_tier\}\}/g, args.schedule || "hourly");

  // Write project YAML
  await fs.mkdir(PROJECTS_DIR, { recursive: true });
  await fs.writeFile(projectYamlPath, yaml, "utf8");
  console.log(`✓ 已创建项目配置: ${projectYamlPath}`);

  // Create summary template
  const summaryPath = path.join(PROJECTS_DIR, `${args.slug}.summary.md`);
  const summaryTemplate = await fs.readFile(path.join(TEMPLATES_DIR, "summary.example.md"), "utf8")
    .catch(() => `# ${args.title}\n\n（待补充项目说明）\n`);
  const summary = summaryTemplate.replace(/\{\{title\}\}/g, args.title).replace(/\{\{slug\}\}/g, args.slug);
  await fs.writeFile(summaryPath, summary, "utf8");
  console.log(`✓ 已创建摘要模板: ${summaryPath}`);

  // Output next steps
  console.log(`
=== 下一步接入说明 ===

1. 在飞书 Base 中创建 "AI 公开导出" 视图
   - 打开目标数据表
   - 点击 + 添加表格视图
   - 命名为: AI 公开导出

2. 给统一飞书应用授予只读权限
   - 在 Base 设置中添加应用为协作者
   - 权限设为: 只读

3. 更新 Base Registry Secret
   - 在 GitHub Secrets 中编辑 FEISHU_BASE_REGISTRY_JSON
   - 添加项目 entry:
     "${args.baseKey}": { "app_token": "<你的 app_token>" }

4. 编辑项目配置
   - 文件: ${projectYamlPath}
   - 添加需要导出的表和字段白名单
   - 参考: config/projects/learning-english.yaml

5. 本地测试 (dry-run)
   FEISHU_APP_ID=... FEISHU_APP_SECRET=... FEISHU_BASE_REGISTRY_JSON='...' \\
   node scripts/sync-project.mjs ${args.slug}

6. 安全扫描
   npm run validate
   npm run security:scan

7. 提交并推送
   git add config/projects/${args.slug}.yaml
   git commit -m "Add project: ${args.title}"
   git push

8. 验证部署
   - 等待 GitHub Actions 运行完成
   - 访问: https://201650545.github.io/feishu-learning-english-export/catalog.json
   - 确认新项目出现在 catalog 中
`);
}

function generateProjectYaml(args) {
  return `# Project: ${args.title}
# Generated by add-project.mjs

config_version: 1

project:
  slug: ${args.slug}
  title: "${args.title}"
  description: "${args.description || ""}"
  group: ${args.group || "general"}
  tags: []
  enabled: true
  status: active

source:
  provider: feishu-bitable
  credential_profile: public-personal
  base_key: ${args.baseKey}
  export_view_name: "AI 公开导出"

table_discovery:
  mode: view-name
  include_tables: []
  exclude_tables: []
  require_export_view: true

export:
  chunk_size: 500
  include_schema: true
  include_summary: true
  include_record_id: true
  stable_sort: true

privacy:
  require_public_flag: false
  public_field_name: "是否公开"
  require_review_status: false
  review_field_name: "公开审核状态"
  approved_value: "已审核"
  scan_free_text: true
  scan_urls: true
  fail_on_sensitive_content: true

schedule:
  tier: ${args.schedule || "hourly"}

compatibility:
  mirror_to_legacy_root: false

tables: []
# 添加表配置，例如:
#   - table_name: "表名"
#     table_slug: english-slug
#     view_name: "AI 公开导出"
#     enabled: true
#     fields:
#       - "字段1"
#       - "字段2"
`;
}

main().catch(e => {
  console.error(`错误：${e.message}`);
  process.exitCode = 1;
});
